FROM node:8

ENV NODE_ENV production

RUN mkdir -p /var/www/app

WORKDIR /var/www/app/

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

COPY . .

RUN npm run build
