FROM node:8

RUN mkdir -p /var/www/app

WORKDIR /var/www/app/

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci

ENV NODE_ENV production

COPY . .

RUN npm run build
